name: muzaia-backend
services:
- name: backend
  source_dir: /
  github:
    branch: main
    deploy_on_push: true
  run_command: python -m uvicorn backend_complete:app --host 0.0.0.0 --port 8080
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /health
  envs:
  - key: GEMINI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: DATABASE_URL
    scope: RUN_TIME
    type: SECRET
  - key: PYTHONPATH
    scope: RUN_TIME
    value: "/app"
  - key: PORT
    scope: RUN_TIME
    value: "8080"
