[phases.setup]
nixPkgs = ["nodejs-20", "python311", "postgresql"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "npm ci",
  "pip install fastapi uvicorn sqlalchemy psycopg2-binary python-multipart python-jose[cryptography] passlib[bcrypt] google-generativeai httpx aiofiles python-docx pypdf2 pytesseract chardet pydantic"
]

[phases.build] 
dependsOn = ["install"]
cmds = [
  "npm run build"
]

[start]
cmd = "python3 start_production.py"